version: '3'
services:
  db:
    image: postgres:alpine
    tty: true
    ports:
      - 5001:5432
    volumes:
      - '/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=employee
